name: currency_translate
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.2
  http: ^0.12.0+4
  flutter_spinkit: "^4.1.1"
  cupertino_icons: ^0.1.2
  rounded_floating_app_bar: ^0.1.0
  font_awesome_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
